export const RECIPE_TEMPLATES = [
  {
    id: 'spinach-strawberry-salad',
    title: 'Ensalada de Espinaca y Frutillas',
    emoji: '🥗',
    triggers: ['spinach', 'strawberr', 'espinaca', 'frutilla'],
    otherIngredients: ['aceite de oliva', 'queso feta', 'nueces', 'vinagre balsámico'],
    steps: [
      'Lava y seca bien las hojas de espinaca.',
      'Corta las frutillas por la mitad.',
      'Desmenuza el queso feta sobre la espinaca.',
      'Rocía con aceite de oliva y vinagre balsámico.',
      'Agrega las nueces y mezcla suavemente antes de servir.',
    ],
  },
  {
    id: 'creamy-spinach-pasta',
    title: 'Pasta Cremosa con Espinaca',
    emoji: '🍝',
    triggers: ['spinach', 'milk', 'espinaca', 'leche'],
    otherIngredients: ['pasta', 'ajo', 'parmesano', 'mantequilla', 'nuez moscada'],
    steps: [
      'Cocina la pasta en agua con sal hasta que esté al dente.',
      'Saltea el ajo picado en mantequilla hasta que dore.',
      'Agrega la espinaca y cocina 2 minutos hasta que se marchite.',
      'Vierte la leche y cocina a fuego lento hasta espesar.',
      'Mezcla con la pasta, el parmesano y una pizca de nuez moscada.',
    ],
  },
  {
    id: 'carrot-ginger-soup',
    title: 'Sopa de Zanahoria y Jengibre',
    emoji: '🍲',
    triggers: ['carrot', 'zanahoria'],
    otherIngredients: ['jengibre', 'cebolla', 'caldo de verduras', 'leche de coco', 'aceite de oliva'],
    steps: [
      'Pica la cebolla y pela las zanahorias.',
      'Saltea la cebolla y el jengibre rallado en aceite hasta que estén tiernos.',
      'Agrega las zanahorias y el caldo, lleva a hervor.',
      'Cocina 20 minutos hasta que las zanahorias estén muy blandas.',
      'Licúa hasta lograr una textura suave, agrega la leche de coco y sazona.',
    ],
  },
  {
    id: 'berry-smoothie-bowl',
    title: 'Bowl de Smoothie de Frutas',
    emoji: '🥤',
    triggers: ['strawberr', 'blueberr', 'banana', 'frutilla', 'arándano'],
    otherIngredients: ['yogur', 'miel', 'granola', 'semillas de chía'],
    steps: [
      'Licúa las frutas con el yogur hasta obtener una mezcla espesa.',
      'Vierte en un bowl amplio.',
      'Esparce granola generosamente por encima.',
      'Agrega las semillas de chía.',
      'Termina con un chorrito de miel y sirve de inmediato.',
    ],
  },
  {
    id: 'cheddar-omelette',
    title: 'Omelette de Queso y Hierbas',
    emoji: '🍳',
    triggers: ['cheese', 'egg', 'queso', 'huevo'],
    otherIngredients: ['huevos', 'mantequilla', 'ciboulette', 'sal', 'pimienta'],
    steps: [
      'Bate 3 huevos con sal y pimienta.',
      'Derrite mantequilla en una sartén antiadherente a fuego medio.',
      'Vierte los huevos y deja cocinar 60 segundos sin revolver.',
      'Agrega el queso rallado sobre una mitad.',
      'Dobla y desliza al plato, decora con ciboulette.',
    ],
  },
  {
    id: 'cinnamon-apple-oatmeal',
    title: 'Avena con Manzana y Canela',
    emoji: '🥣',
    triggers: ['apple', 'manzana'],
    otherIngredients: ['avena', 'leche', 'azúcar morena', 'canela', 'mantequilla'],
    steps: [
      'Corta la manzana en cubos pequeños.',
      'Lleva la leche a hervor suave en una cacerola pequeña.',
      'Agrega la avena y cocina 5 minutos revolviendo.',
      'Incorpora la manzana, el azúcar morena y la canela.',
      'Cocina 3 minutos más hasta que la manzana ablande. Termina con mantequilla.',
    ],
  },
  {
    id: 'veggie-stir-fry',
    title: 'Salteado de Verduras de Colores',
    emoji: '🥘',
    triggers: ['carrot', 'broccoli', 'pepper', 'mushroom', 'cabbage', 'spinach', 'zanahoria', 'brócoli', 'pimiento', 'espinaca'],
    otherIngredients: ['salsa de soja', 'ajo', 'jengibre', 'aceite de sésamo', 'arroz jazmín'],
    steps: [
      'Cocina el arroz según las instrucciones del paquete.',
      'Calienta aceite de sésamo en un wok a fuego alto.',
      'Agrega las verduras y saltea 3–4 minutos.',
      'Añade salsa de soja, ajo picado y jengibre rallado.',
      'Mezcla bien y sirve de inmediato sobre el arroz.',
    ],
  },
  {
    id: 'fluffy-milk-pancakes',
    title: 'Panqueques Esponjosos con Leche',
    emoji: '🥞',
    triggers: ['milk', 'egg', 'leche', 'huevo'],
    otherIngredients: ['harina', 'polvo de hornear', 'azúcar', 'mantequilla', 'jarabe de arce'],
    steps: [
      'Mezcla la harina, el polvo de hornear y el azúcar.',
      'En otro bowl, bate la leche, los huevos y la mantequilla derretida.',
      'Incorpora los ingredientes húmedos a los secos con movimientos suaves.',
      'Cocina a fuego medio hasta que aparezcan burbujas, luego voltea.',
      'Sirve apilados con mantequilla y jarabe de arce.',
    ],
  },
  {
    id: 'cheese-quesadilla',
    title: 'Quesadilla de Queso',
    emoji: '🫓',
    triggers: ['cheese', 'queso'],
    otherIngredients: ['tortillas', 'crema agria', 'salsa', 'aguacate'],
    steps: [
      'Ralla el queso generosamente.',
      'Coloca el queso sobre la mitad de una tortilla grande.',
      'Dobla por la mitad y pon en una sartén seca.',
      'Cocina 2 minutos por lado hasta que esté dorada.',
      'Corta en triángulos y sirve con salsa, crema agria y aguacate.',
    ],
  },
  {
    id: 'apple-cheese-board',
    title: 'Tabla de Manzana y Queso',
    emoji: '🧀',
    triggers: ['apple', 'cheese', 'manzana', 'queso'],
    otherIngredients: ['galletas', 'miel', 'nueces', 'arándanos secos'],
    steps: [
      'Corta la manzana en rodajas finas.',
      'Corta o desmenuza el queso.',
      'Acomoda la manzana y el queso en una tabla.',
      'Rellena los espacios con galletas, nueces y arándanos.',
      'Termina con un chorrito de miel.',
    ],
  },
  {
    id: 'milk-rice-pudding',
    title: 'Arroz con Leche a la Vainilla',
    emoji: '🍮',
    triggers: ['milk', 'leche'],
    otherIngredients: ['arroz de grano corto', 'azúcar', 'esencia de vainilla', 'canela'],
    steps: [
      'Combina el arroz y la leche en una cacerola.',
      'Lleva a hervor suave revolviendo con frecuencia.',
      'Cocina 20–25 minutos hasta que esté espeso y cremoso.',
      'Retira del fuego, agrega el azúcar y la vainilla.',
      'Sirve tibio o frío, espolvorea con canela.',
    ],
  },
  {
    id: 'carrot-milk-soup',
    title: 'Sopa Cremosa de Zanahoria',
    emoji: '🥛',
    triggers: ['carrot', 'milk', 'zanahoria', 'leche'],
    otherIngredients: ['cebolla', 'mantequilla', 'caldo de verduras', 'nuez moscada', 'ciboulette'],
    steps: [
      'Saltea la cebolla picada en mantequilla hasta que esté tierna.',
      'Agrega las zanahorias en rodajas y el caldo de verduras.',
      'Cocina 15 minutos hasta que las zanahorias estén blandas.',
      'Licúa hasta lograr textura suave, luego incorpora la leche.',
      'Sazona con nuez moscada y decora con ciboulette.',
    ],
  },
]
