export const RECIPE_TEMPLATES = [
  {
    id: 'spinach-strawberry-salad',
    title: 'Spinach & Strawberry Salad',
    emoji: '🥗',
    triggers: ['spinach', 'strawberr'],
    otherIngredients: ['olive oil', 'feta cheese', 'walnuts', 'balsamic vinegar'],
    steps: [
      'Wash and dry spinach leaves thoroughly.',
      'Slice strawberries in half.',
      'Crumble feta cheese over the spinach.',
      'Drizzle with olive oil and balsamic vinegar.',
      'Top with walnuts and toss gently to serve.',
    ],
  },
  {
    id: 'creamy-spinach-pasta',
    title: 'Creamy Spinach Pasta',
    emoji: '🍝',
    triggers: ['spinach', 'milk'],
    otherIngredients: ['pasta', 'garlic', 'parmesan', 'butter', 'nutmeg'],
    steps: [
      'Cook pasta in salted boiling water until al dente.',
      'Sauté minced garlic in butter until fragrant.',
      'Add spinach and wilt for 2 minutes.',
      'Pour in milk and simmer until slightly thickened.',
      'Toss with pasta, parmesan and a pinch of nutmeg.',
    ],
  },
  {
    id: 'carrot-ginger-soup',
    title: 'Carrot Ginger Soup',
    emoji: '🍲',
    triggers: ['carrot'],
    otherIngredients: ['ginger', 'onion', 'vegetable broth', 'coconut milk', 'olive oil'],
    steps: [
      'Dice onion and peel carrots into chunks.',
      'Sauté onion and grated ginger in olive oil until soft.',
      'Add carrots and vegetable broth, bring to a boil.',
      'Simmer 20 minutes until carrots are very tender.',
      'Blend until smooth, stir in coconut milk and season.',
    ],
  },
  {
    id: 'berry-smoothie-bowl',
    title: 'Berry Smoothie Bowl',
    emoji: '🥤',
    triggers: ['strawberr', 'blueberr', 'banana'],
    otherIngredients: ['yogurt', 'honey', 'granola', 'chia seeds'],
    steps: [
      'Blend fruit with yogurt until thick and smooth.',
      'Pour into a wide bowl.',
      'Scatter granola generously over the top.',
      'Sprinkle with chia seeds.',
      'Drizzle with honey and serve immediately.',
    ],
  },
  {
    id: 'cheddar-omelette',
    title: 'Cheddar Herb Omelette',
    emoji: '🍳',
    triggers: ['cheese', 'egg'],
    otherIngredients: ['eggs', 'butter', 'chives', 'salt', 'pepper'],
    steps: [
      'Beat 3 eggs with a pinch of salt and pepper.',
      'Melt butter in a non-stick pan over medium heat.',
      'Pour in eggs and let set for 60 seconds without stirring.',
      'Scatter grated cheddar over one half.',
      'Fold and slide onto a plate, garnish with chives.',
    ],
  },
  {
    id: 'cinnamon-apple-oatmeal',
    title: 'Cinnamon Apple Oatmeal',
    emoji: '🥣',
    triggers: ['apple'],
    otherIngredients: ['rolled oats', 'milk', 'brown sugar', 'cinnamon', 'butter'],
    steps: [
      'Dice apple into small cubes.',
      'Bring milk to a gentle simmer in a small saucepan.',
      'Stir in rolled oats and cook for 5 minutes.',
      'Add diced apple, brown sugar and cinnamon.',
      'Cook 3 more minutes until apple softens. Finish with butter.',
    ],
  },
  {
    id: 'veggie-stir-fry',
    title: 'Rainbow Veggie Stir Fry',
    emoji: '🥘',
    triggers: ['carrot', 'broccoli', 'pepper', 'mushroom', 'cabbage', 'spinach'],
    otherIngredients: ['soy sauce', 'garlic', 'ginger', 'sesame oil', 'jasmine rice'],
    steps: [
      'Cook jasmine rice according to package directions.',
      'Heat sesame oil in a wok over high heat until smoking.',
      'Add vegetables and stir fry for 3–4 minutes.',
      'Add soy sauce, minced garlic and grated ginger.',
      'Toss well and serve immediately over rice.',
    ],
  },
  {
    id: 'fluffy-milk-pancakes',
    title: 'Fluffy Milk Pancakes',
    emoji: '🥞',
    triggers: ['milk', 'egg'],
    otherIngredients: ['flour', 'baking powder', 'sugar', 'butter', 'maple syrup'],
    steps: [
      'Whisk together flour, baking powder and a pinch of sugar.',
      'In another bowl, whisk milk, eggs and melted butter.',
      'Gently fold wet into dry ingredients until just combined.',
      'Cook on medium heat until bubbles form, then flip.',
      'Serve stacked with butter and maple syrup.',
    ],
  },
  {
    id: 'cheese-quesadilla',
    title: 'Loaded Cheese Quesadilla',
    emoji: '🫓',
    triggers: ['cheese'],
    otherIngredients: ['tortillas', 'sour cream', 'salsa', 'avocado'],
    steps: [
      'Grate cheddar generously.',
      'Lay cheese over one half of a large tortilla.',
      'Fold in half and place in a dry frying pan.',
      'Cook 2 minutes per side until golden brown.',
      'Cut into wedges and serve with salsa, sour cream and avocado.',
    ],
  },
  {
    id: 'apple-cheese-board',
    title: 'Apple & Cheese Snack Board',
    emoji: '🧀',
    triggers: ['apple', 'cheese'],
    otherIngredients: ['crackers', 'honey', 'walnuts', 'dried cranberries'],
    steps: [
      'Slice apple into thin wedges.',
      'Cube or crumble the cheese.',
      'Arrange apple and cheese on a board.',
      'Fill gaps with crackers, walnuts and cranberries.',
      'Finish with a drizzle of honey.',
    ],
  },
  {
    id: 'milk-rice-pudding',
    title: 'Vanilla Rice Pudding',
    emoji: '🍮',
    triggers: ['milk'],
    otherIngredients: ['short-grain rice', 'sugar', 'vanilla extract', 'cinnamon'],
    steps: [
      'Combine short-grain rice and milk in a heavy saucepan.',
      'Bring to a gentle simmer, stirring frequently.',
      'Cook 20–25 minutes until thick and creamy.',
      'Remove from heat, stir in sugar and vanilla.',
      'Serve warm or cold, dusted with cinnamon.',
    ],
  },
  {
    id: 'carrot-milk-soup',
    title: 'Creamy Carrot & Milk Soup',
    emoji: '🥛',
    triggers: ['carrot', 'milk'],
    otherIngredients: ['onion', 'butter', 'vegetable broth', 'nutmeg', 'chives'],
    steps: [
      'Sauté diced onion in butter until soft.',
      'Add sliced carrots and vegetable broth.',
      'Simmer 15 minutes until carrots are tender.',
      'Blend until smooth, then stir in milk.',
      'Season with nutmeg, garnish with chives.',
    ],
  },
]
